name: 'coverage'
on:
  pull_request:
      branches:
          - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Run codacy-coverage 
              uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}