name: Code Climate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-climate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Run Code Climate analysis
        env:
          CODECLIMATE_REPO_TOKEN: ${{ secrets.CODECLIMATE_REPO_TOKEN }}
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
          ./cc-test-reporter analyze --exit-code ${{ steps.tests.outcome }}

      - name: Upload coverage report to Code Climate
        env:
          CODECLIMATE_REPO_TOKEN: ${{ secrets.CODECLIMATE_REPO_TOKEN }}
        run: |
          ./cc-test-reporter format-coverage -t simplecov -o coverage/codeclimate.json
          ./cc-test-reporter upload-coverage

      - name: Code Climate Analysis
        env:
          CODECLIMATE_REPO_TOKEN: ${{ secrets.CODECLIMATE_REPO_TOKEN }}
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
          find ./projects -type f \( -name "*.css" -o -name "*.js" -o -name "*.html" \) -exec ./cc-test-reporter analyze --engine eslint --path {} \;
          ./cc-test-reporter after-build --exit-code ${{ steps.tests.outcome }}
