name: Jsdocs
on:
  push:
    branches:
      - main

jobs:
  tests: 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4 #
      - name: Install Dependencies
        run: npm install
      - name: Install JSDoc
        run: npm install -g jsdoc
        
      - name: Build JSDoc for Project
        run: jsdoc ./project -d ./docs
      - name: Create Pull Request for update JSDoc
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-jsdoc
          title: Update JSDoc documentation
          body: |
            This pull request updates the JSDoc documentation.
          commit-message: Update JSDoc documentation
