name: JSDoc

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  

    - name: Install Dependencies
      run: npm install  

    - name: Generate JSDoc
      run: npx jsdoc -c jsdoc.json  # Assumes you have a jsdoc.json configuration file

    - name: Deploy to GitHub Pages  # Optional step to deploy docs to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./project/docs  # Set this to your JSDoc output directory

