name: JSDoc Documentation

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify your Node.js version

    - name: Install dependencies
      run: npm install  # Adjust if you use a package manager like yarn

    - name: Generate JSDoc
      run: npx jsdoc -c jsdoc.json

    - name: Deploy Documentation to GitHub Pages  # Optional deployment step
      if: github.ref == 'refs/heads/main'  # Runs only on the main branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./project/docs  # Ensure this matches the output directory in your jsdoc.json


